openapi: 3.0.0
info:
  title: revison of yaml
  version: 1.0.0
  description: API for managing example api

servers:
  - url: http://localhost:500

paths:

  /signup:
    get:
      summary: Get the login page
      responses:
        200:
          description: enter details

    post:
      summary: enter details to login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - password
                - email
              properties:
                name:
                  type: string
                  example: ayush
               
                password:
                  type: string
                  example: 12345
                email:
                  type: string
                  example: ayush@mail
      responses:
        200:
          description: Event created

  /bookings:
    post:
      summary: Book tickets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - event_id
                - tickets
              properties:
                user_id:
                  type: integer
                  example: 1
                event_id:
                  type: integer
                  example: 2
                tickets:
                  type: integer
                  example: 1
      responses:
        200:
          description: Booking successful
        400:
          description: Error occurred

  /users/{id}/bookings:
    get:
      summary: Get bookings of user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        200:
          description: List of bookings

  /events/{id}/attendance:
    post:
      summary: Mark attendance
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - code
              properties:
                code:
                  type: string
                  example: abc123xyz
      responses:
        200:
          description: Attendance marked
        404:
          description: Invalid code